version: '3'
services:
  parser:
    image: djandr/drain-parser-api:latest
    container_name: drain_lp
    volumes:
      - shared_volume:/logparser/data/
    restart: always
    ports:
      - "40001:40001"
    networks:
      - lp_net
      
  detector:
    image: djandr/pca-ad-api:latest
    container_name: pca_ad
    volumes:
      - shared_volume:/data/
    ports:
      - "50001:50001"
    restart: always
    networks:
      - ad_net
  
  mw_proposer:
    image: djandr/middleware_ds:latest
    container_name: proposer
    volumes:
      - ./endpoint_device:/home/app
    ports:
      - "60001:60001"
    restart: always
    environment:
      - IP_LIST=147.100.4.5:60001,147.100.4.2:60001,147.100.4.3:60001,147.100.4.4:60001,147.100.4.5:60001,147.100.4.6:60001,147.100.4.7:60001
      - LP_IP_RANGE=145.100.2.1-145.100.2.5
      - AD_IP_RANGE=146.100.3.1-146.100.3.5
      - LAST_ACCEPTED=147.100.4.2
      - CURRENT_LP_REQ_ID=0
      - CURRENT_AD_REQ_ID=0
      - PROMISED_TO_ACCEPT=-1
      - PAXOS_ROLE=P
      - PORT=60001
    networks:
      - mw_net
  
volumes:
  external:
    - shared_volume
 
networks: 
  lp_net: 
    external: true
  ad_net: 
    external: true
  mw_net: 
    external: true
 
#correr el listener en segundo plano:
# nohup python3 listener_run.py &
